db.write.url=jdbc:postgresql://localhost:5677/faisal_db
db.write.username=faisal_user
db.write.password=Z1s152easpwu

db.read.url=jdbc:postgresql://localhost:5677/faisal_db
db.read.username=faisal_user
db.read.password=Z1s152easpwu