spring.application.name=auth-service

spring.profiles.active=dev
server.port=9701

#spring.main.banner-mode=off
#logging.level.root=warn

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.key=${JWT_KEY:JUJUTSU_KAISEN_SHIBUYA_ARC_ITADORI_YUJI}
token-name=BEARER_TOKEN_MOC_DEV

# 900,000 ms = 15M (Access Token)
jwt.access-token-expiration=900000
# 604,800,000 ms = 7D (Refresh Token)
jwt.refresh-token-expiration=604800000