spring.application.name=auth-service

spring.profiles.active=dev
server.port=9701

#spring.main.banner-mode=off
#logging.level.root=warn

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.key=${JWT_KEY:JUJUTSU_KAISEN_SHIBUYA_ARC_ITADORI_YUJI}
token-name=BEARER_TOKEN_MOC_DEV

# 360,000,000 ms = 100 h (Access Token)
jwt.access-token-expiration=360000000
# 8,640,000,000 ms = 100 d (Refresh Token)
jwt.refresh-token-expiration=8640000000