spring.application.name=auth-service

spring.profiles.active=dev
#spring.main.banner-mode=off
#logging.level.root=warn

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.key=${JWT_KEY:JUJUTSU_KAISEN_SHIBUYA_ARC_ITADORI_YUJI}
jwt.access-token-expiration=360000000